from .home import home
from .parks.list import park_list
from .parks.form import park_form
from .parks.details import park_details
from .parks.form import park_edit_form
from .discs.list import disc_list
from .discs.form import disc_form
from .discs.details import disc_details
from .discs.form import disc_edit_form
from .bags.list import bag_list
from .bags.form import bag_form
from .bags.details import bag_details
from .games.list import game_list
from .games.details import game_details
from .games.form import game_form
from .games.form import game_edit_form
from .account.details import account_details
from .account.form import account_edit_form