# Generated by Django 3.0.7 on 2020-06-16 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'bag',
                'verbose_name_plural': 'bags',
            },
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_type', models.CharField(choices=[('Driver', 'Driver'), ('Mid-Range', 'Midrange'), ('Putter', 'Putter')], max_length=20)),
                ('color', models.CharField(max_length=20, null=True)),
                ('speed', models.IntegerField(null=True)),
                ('glide', models.IntegerField(null=True)),
                ('turn', models.IntegerField(null=True)),
                ('fade', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'disc',
                'verbose_name_plural': 'discs',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'park',
                'verbose_name_plural': 'parks',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reciever', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('bag_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BirdieApp.Bag')),
                ('park_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BirdieApp.Park')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.AddField(
            model_name='bag',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BirdieApp.Disc'),
        ),
    ]
