# Generated by Django 3.0.7 on 2020-06-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='brand',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
