# Generated by Django 3.0.7 on 2020-06-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BirdieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='bag_id',
            new_name='bag',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='park_id',
            new_name='park',
        ),
    ]
