# Generated by Django 3.0.7 on 2020-06-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BirdieApp', '0002_auto_20200616_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='disc',
            name='disc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BirdieApp.Disc_Type'),
        ),
    ]
