# Generated by Django 3.0.7 on 2020-06-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdieApp', '0005_auto_20200622_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
