# Generated by Django 3.0.7 on 2020-06-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdieApp', '0006_auto_20200622_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
